function exibeTutorial(valor){


    if(valor == 1){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Como Jogar</h2><br><br><br><p>O Pula Prédios é um game do gênero endless runner, onde o jogador só para de correr ao morrer.</p><h2 class='nome_tutorial' style='color: red;'>NÃO MORRA</h2><br><br><br><p>Custe o que custar, pule os obstáculos a frente e não morra! Use o <a href='#' onclick='exibeTutorial("+ 2 +")'>especial</a> nos momentos arriscados e corra o máximo possível.</p><h2 class='nome_tutorial'>Infos</h2><br><br><br><p>Caso sinta necessidade, não hesite em abrir os <a href='#' onclick='botoes("+ 99 +")'>controles</a> para visualizar uns comandos!</p>";
    }
    
    if(valor == 2){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Especial</h2><br><br><br><p>O especial é um recurso secundário que pode ser ativado pressionando D ou Enter enquanto você estiver numa partida.</p><h2 class='nome_tutorial'>Uso</h2><br><br><br><p>Ao utilizar o especial você irá flutuar por um período de 5 segundos, evitando morrer ao atropelar construções ou ao cair na água e lava.</p> <h2 class='nome_tutorial'>Recarregamento</h2><br><br><br><p>Seu tempo de recarga demora 10 segundos para completar, enquanto estiver nesse estado o jogador será poupado de eventos aquáticos ou de lava.</p><h2 class='nome_tutorial'>Atençõn (!)</h2><br><br><br><p>O Especial possuí um limite de usos por partida! Então use com sabedoria. Caso queira saber onde ver, o total é mostrado <span style='color: greenyellow;'>com esta cor</span>, na caixa do especial ;)</p><h2 class='nome_tutorial'>Incrementos</h2><br><br><br><p>O Especial pode ser modificado com o uso de <a href='#' onclick='exibeTutorial(12)'>modificadores</a>, para consultar mais detalhes consulte a aba de modificadores.</p><h2 class='nome_tutorial'>Curiosidades</h2><br><br><br><p>O especial foi introduzido pela primeira vez na versão Alpha 0.01, na primeira versão do Pula Prédios!</p>";
    }

    if(valor == 3){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Inimigos</h2><br><br><br><p>Os 'inimigos' são a maioria por aqui, eles podem ser desde prédios até ao piso onde você está prestes a pisar!</p><h2 class='nome_tutorial'>Inimigos conhecidos</h2><br><br><br><img src='Imagens/Sprites/Cidade/Predio1_2.png'> &nbsp; &nbsp; <img src='Imagens/Sprites/Cidade/Predio2_2.png'> &nbsp; &nbsp; <img src='Imagens/Sprites/Cidade/Predio3.png'><br><br><p style='color: red;'>(!) A Versão sem antena também é perigosa</p><h2 class='nome_tutorial'>Cuidados</h2><br><br><br><p>Caso você atropele um prédio enquanto estiver com o <a href='#' onclick='exibeTutorial("+ 2 +")'>especial</a> ativo, você perderá pontos!</p><h2 class='nome_tutorial'>Outras construções</h2><br><br><br><p>Caso não tenha morrido ao atropelar uma construção e tenha ficado com a pulga atrás da orelha, confira o artigo das <a href='#' onclick='exibeTutorial("+ 5 +")'>moedas</a>.</p><h2 class='nome_tutorial'>Curiosidades</h2><br><br><br><p>Até a versão Alpha 0.04 os inimigos tinham uma aparência assombrada de noite, como as imagens abaixo \\\\//</p><img src='Imagens/Sprites/Acervo/predio1_2.png'> &nbsp; &nbsp; <img src='Imagens/Sprites/Acervo/predio3.png'>";
    }

    if(valor == 4){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Eventos</h2><br><br><br><p>Há vários eventos no game, eles são ativados de tempos em tempos e tem suas características próprias!<br><br>Apenas sobreviva a eles e ganhará umas estatísticas a+ :v</p> <h2 class='nome_tutorial'>São eles \\\\//</h2><br><br><br><p style='color: cyan;'>Área Densa</p><p>Concentra muitos prédios e uma poluição visual gigante!</p><hr style='width: 250px;'><p style='color: cyan'>Parque</p><p>Aqui você poderá ganhar muitos pontos destruindo pisões ajudando a limpar o parque.</p><hr style='width: 250px;'><p style='color: cyan'>Água</p><p>Toda cidade possui rios ou lagos e aqui não será diferente! Pule eles ou afunda ;D</p><hr style='width: 250px;'><p style='color: cyan'>Lava</><p>Não sabemos como surgiram no game, apenas que ela está lá!</p><h2 class='nome_tutorial'>Curiosidades</h2><br><br><br><p>Eventos foram introduzidos pela 1° vez na versão Beta 1.0, vindo de uma variação de um sistema de níveis. Os níveis eram usados na Alpha 0.04 para acelerar o jogador com o decorrer do tempo.</p>";
    }
''
    if(valor == 5){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Moedas</h2><br><br><br><p>A única forma de ganhar moedas no game é destruindo pisões. Pisões são construções abandonadas que possuem 2 variantes, pise neles e se eles tiverem alguma moeda você ganhará!</p><h2 class='nome_tutorial'>Variantes Conhecidas</h2><br><br><br><img src='Imagens/Sprites/Cidade/Pisao_noite.png'> &nbsp; &nbsp; <img src='Imagens/Sprites/Cidade/Pisao2_noite.png'><br><br><h2 class='nome_tutorial'>Usos</h2><br><br><br><p>Moedas podem ser usadas para comprar alguns bônus e atualizar sua skin na <a href='#' onclick='exibeTutorial("+ 6 +")'>loja</a>.</p><h2 class='nome_tutorial'>Curiosidades</h2><br><br><br><p>Pisões podem conter ou não moedas, no <a href='#' onclick='exibeTutorial("+ 4 +")'>evento</a> de área densa, os pisões podem dar até 8 moedas.</p>";
    }

    if(valor == 6){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Loja</h2><br><br><br><p>A <a href='#' onclick='botoes("+ 120 +")'>loja</a> é onde você pode gastar suas moedas! Por lá é possível comprar novas cores para sua skin ou dar um upgrade em seu especial!</p><h2 class='nome_tutorial'>Esquema de Cores</h2><br><br><br><p>Adotamos 3 cores para usar na loja<img src='Imagens/Atualiza/loja.png'>Amarelo: Para itens que você comprou e equipou.<br><br>Verde: Para itens comprados.<br><br>Azul Escuro: Para itens à venda.</p><h2 class='nome_tutorial'>Incrementos</h2><br><br><br>Incrementos p/ Especiais comprados são automaticamente ativados, podendo ser apenas azul escuro ou amarelo.</p><h2 class='nome_tutorial'>Curiosidades</h2><br><br><br><p>A loja e o sistema de skins foram pensados para serem implementados na versão Beta 2.0, porém foram postergados para a Beta 3.0 pela complexidade envolvida.</p><h2 class='nome_tutorial' style='color: red;'>Recurso Experimental</h2><br><br><br><p>Alguns itens da loja como os Modificadores, se tratam de recursos experimentais, eles podem funcionar mas não garantimos que irão funcionar corretamente em 100% do tempo.</p>";
    }

    if(valor == 7){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Teclas de Atalho</h2><br><br><br><p>Algumas teclas de atalho estão presentes no game, elas podem ser usadas para evitar percorrer algumas telas ;)<br> Você pode conferir as teclas de atalho diretamento nos <a href='#' onclick='botoes("+ 99 +")'>controles</a><br> <span style='color: red'>( elas estão destacadas em vermelho )</span></p>";
    }

    if(valor == 8){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Dificuldade</h2><br><br><br><p>A dificuldade pode ser alterada nas <a href='#' onclick='botoes("+ 122 +")'>configurações</a> enquanto estiver no menu, há 4 níveis de dificuldade presentes no jogo.</p><h2 class='nome_tutorial'>São Elas \\\\//</h2><br><br><br><p style='color: cyan'>Fácil</p><p>Proporciona um jogo leve para o player, indicado para iniciantes.</p><hr style='width: 250px;'><p style='color: cyan'>Normal</p><p>Essa é a dificuldade padrão do jogo</p><hr style='width: 250px;'><p style='color: cyan'>Difícil</p><p>É um pouco mais complicado que o normal, proporciona um desafio a mais ao jogador</p><hr style='width: 250px;'><p style='color: cyan'>Expert</p><p>Sobreviver nessa dificuldade é uma dádiva para poucos, mas suas recompensas são gratificantes.</p><h2 class='nome_tutorial'>Atençõn (!)</h2><br><br><br><p>As <a href='#' onclick='botoes("+ 5 +")'>moedas</a> e os pisões estão relacionados diretamente com a dificuldade que você estiver jogando, quanto mais fácil, você verá mais pisões e receberá menos moedas, quanto mais difícil, serão menos pisões e muito mais moedas!</p>";
    }

    if(valor == 9){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Configurações</h2><br><br><br><p>As configurações podem ser acessadas pressionando a tecla ( Z ), elas permitem modificar alguns comportamentos do jogo que estão listados abaixo</p><h2 class='nome_tutorial'>Opções \\\\//</h2><br><br><br><p style='color: cyan'>Sons</><p>Há como ativar, desativar e regular o volume de alguns sons do game caso necessário</p><hr style='width: 250px;'><p style='color: cyan'>Dificuldade</p><p>É possivel alterar a dificuldade, ela varia em 4 níveis diferentes, com suas característiscas.</p><hr style='width: 250px;'><p style='color: cyan'>Tela de Morte</p><p>Uma nova tela de estatísticas foi incluída no game, caso não queira vê-la ao morrer, pode ser desativada.</p><hr style='width: 250px;'><p style='color: cyan'>Tema</p><p>Com esta opção é possível travar o tema do jogo em diurno, noturno ou deixar padrão como 'dinâmico'.</p><hr style='width: 250px;'><p style='color: cyan'>Modo Ocioso</p><p>O Modo ocioso trás ao jogador uma opção de um plano de fundo, ele passará diversos itens na tela, simulando um jogo ativo, é possível desativar ele.</p><hr style='width: 250px;'><p style='color: cyan'>Estatísticas para Nerds</p><p>Esta opção irá fazer com que o jogo crie relatórios no console do navegador <span style='color: yellow'>( acessível pressionando a tecla F12 )</span>, com ela ativa você poderá ver vários feedbacks enquanto o jogo é executado.</p><h2 class='nome_tutorial' style='color: red;'>Recurso Experimental</h2><br><br><br><p>O Modo ocioso é um recurso que ainda é <a href='#' onclick='exibeTutorial("+ 10 +")'>experimental</a>, sendo assim, ele pode trazer um funcionamento inesperado.</p>";
    }

    if(valor == 10){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Recursos Experimentais</h2><br><br><br><p>Há alguns recursos experimentais no jogo, eles são planejados para serem adicionados e já estão no game, porém podem não apresentar o funcionamento esperado às vezes.</p><h2 class='nome_tutorial'>Cuidados</h2><br><br><br><p>Recursos experimentais podem ser ativados, porém aconselha-se ativá-los apenas para fim de testes e visualização prévia.</p>";
    }

    if(valor == 11){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Estatísticas para Nerds</h2><br><br><br><p>Essas estatísticas são um aglomerado de várias informações que podem ser vistas através do console do navegador, caso queira ver o jogo funcionando em detalhes mais técnicos ative ela e abra o console. ( pressionando F12 )</p>";
    }

    if(valor == 12){
        document.getElementById("item_selecionado").innerHTML = "<h2 class='nome_tutorial'>Modificadores</h2><br><br><br><p>São itens compráveis que podem ser usados durante suas partidas, eles irão modificar a forma como seu jogo irá funcionar, porém só serão válidos pelas próximas 5 partidas.</p><img src='Imagens/Atualiza/mods.png'><br><br><p>Modificadores no momento são recursos destinados apenas ao especial, e eles podem acrescentar tempo e vezes de uso em suas partidas.</p><h2 class='nome_tutorial' style='color: red;'>Recurso Experimental</h2><br><br><br><p>Os Modificadores ainda são reconhecidos como recursos experimentais, sendo assim, eles podem funcionar mas não garantimos que irão funcionar corretamente em 100% do tempo.</p>";
    }

    $("#tutoriais_2").animate({ scrollTop: 0 }, "slow");
}